# Generated by Django 5.2.8 on 2025-11-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='statuse',
            field=models.CharField(choices=[('1', 'yomon'), ('2', 'yaxshi'), ('3', 'alo'), ('4', 'super')], default='2'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
